version: '3.7'
networks:
  insbackend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.223.0/28

volumes:
  postgres:
  redis:

services:
  db:
    container_name: "ins_db"
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "${DB_PORTS}"
    environment:
      POSTGRES_DB: insurance
      POSTGRES_USER: insurance
      POSTGRES_PASSWORD: insurance
    networks:
      - insbackend
  nginx:
    image: nginx:1.17.5-alpine
    restart: on-failure
    volumes:
      - './laravel/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "${NGINX_PORTS}"
    depends_on:
      - php
    networks:
      - insbackend
    container_name: "ins_nginx"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    user: 1000:1000
    networks:
      - insbackend
    container_name: "ins_laravel"
    volumes:
      - './laravel/:/usr/src/app'
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.223.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
  redis:
    container_name: "ins_redis"
    image: redis:5.0.7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORTS}"
    hostname: "${REDIS_HOST}"
    networks:
      - insbackend